### ISSUE TITLE
yarn serve and npm run serve run development build

### ISSUE THREAD

**Issue by theSdev** [mlwilkerson/vue-fontawesome-tree-shaking-demo#1]
yarn serve and npm run serve run development build which is not optimized so it doesn't use tree-shaking.
As noted in [this StackOverflow answer](https://stackoverflow.com/a/47034557/6676654), production build can be run by 

> npm install -g serve
> serve -s dist

Maybe you want to update the readme file with that info
Thanks.

**Comment by mlwilkerson** [comment]
Yes, sorry about that. Fixed.
